name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 60
    runs-on: buildjet-8vcpu-ubuntu-2204
    container: mcr.microsoft.com/playwright:v1.55.0-noble
    steps:
      - name: Checkout ref
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
