name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 60
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Checkout ref
        uses: actions/checkout@v4
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: buildjet/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup node
        uses: buildjet/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn-cache
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
